default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['REGULUS_DATABASE_USERNAME'] %>
  passwprd: <%= ENV['REGULUS_DATABASE_PASSWORD'] %>
development:
  <<: *default
  database: regulus_development
test:
  <<: *default
  database: regulus_test
production:
  <<: *default
  database: regulus_production
